### ISSUE TITLE
Ollama AI Integration

### ISSUE THREAD

**Issue by mwsmith824** [biblioverse/biblioteca#235]
Are there any plans to integrate with Ollama for selfhosted AI tagging as opposed to OpenAI? Would be great to keep everything localized.

**Comment by SergioMendolia** [comment]
I haven't planned that, but that would certainly make sense and that sounds like an interesting holidays project

**Comment by SergioMendolia** [comment]
@mwsmith824 I just published a release with the ollama integration! Happy holidays!

**Comment by mwsmith824** [comment]
That was fast! Thank you sir and happy holidays!

**Comment by SergioMendolia** [comment]
It was surprisingly a lot easier than I expected ;)
