### ISSUE TITLE
Can we remove kepubify installation from test suite?

### ISSUE THREAD

**Issue by SergioMendolia** [biblioverse/biblioteca#239]

**Comment by ragusa87** [comment]
You can, but then you need to remove the phpunit tests that uses Kepubify or mock the class so it doesn't have to call the kepubify binary.

**Comment by SergioMendolia** [comment]
@ragusa87 but the binary is already in the image, so why download it a second time?

**Comment by ragusa87** [comment]
Well, I would say that I added it in the pipeline as it's wasn't in the image at the time, or because the path was misconfigured. Or because the docker image was not used. I don't know. 

I can indeed have a fresh look

**Comment by SergioMendolia** [comment]
I tried and realised that we are indeed not using the image. it's closed, thanks
