### ISSUE TITLE
errors when scanning books

### ISSUE THREAD

**Issue by onigoetz** [biblioverse/biblioteca#99]
Hi, nice tool you got there :)

I'm running my first scan and I have lots of errors and no way to know from where they come. Here's an excerpt

```
Command Line Error:
Unknown switch:
-


Command Line Error:
Unknown switch:
-
sh: 1: Syntax error: Unterminated quoted string
sh: 1: Syntax error: Unterminated quoted string

Syntax error: "(" unexpected
sh: 1: Syntax error: "(" unexpected

ERROR: No more files
/var/www/html/public/books/BD/Le

System ERROR:
Unknown error -2147024872
```

I guess that I have special characters in my files but not sure which files. Also the "no more files" seems to indicate that I have a path with a space in it, but the parameter isn't quoted or the space not escaped

I'd be happy to help debug it and send a PR once I figure out what's going on. my hunch is that there is something with escaping paths when passing them to the command line.

Do you have a pointer where I should start looking into this?

**Comment by SergioMendolia** [comment]
Can you run the command with the `-vvv` flag and show me the result?
